import type { ClassItem } from '@/types/tier-list'

const API_BASE_URL = 'https://api.heishabox.com/v1'
const MOCK_GET_GLOBAL = 'https://bd.dvg.cn/tools/api_r'
// const API_BASE_URL="http://localhost:8080/v1"
// const API_BASE_URL="http://localhost:5000"
const BASE_ASSET_URL = 'https://garmoth-assets.oss-cn-shanghai.aliyuncs.com/prod/'
const BASE_IMAGE_URL = 'https://garmoth-assets.oss-cn-shanghai.aliyuncs.com/Productions/'
const BASE_PA_IMAGE_URL = 'https://garmoth-assets.oss-cn-shanghai.aliyuncs.com/prod/pa/'
const BASE_IMAGE_BEAUTY_ALBUM_COVER_URL = 'https://garmoth-assets.oss-cn-shanghai.aliyuncs.com/prod/beauty-album/'
const BASE_IMAGE_CLASS_URL = 'https://garmoth-assets.oss-cn-shanghai.aliyuncs.com/prod/class/'
const APP_NAME = 'Garmon'
const APP_SUFFIX = 'BDO Companion'
const WEBSITE_DOMAIN = 'heishabox.com'
const SCHEMA = {
  '@context': 'https://heishabox.com',
  '@type': 'WebSite',
  'name': '黑沙盒子',
  'url': 'http://heishabox.com',
  'potentialAction': {
    '@type': 'SearchAction',
    'target': 'http://heishabox.com/search?q={search_term_string}',
    'query-input': 'required name=search_term',
  },
}

interface ClassTranslations {
  [key: string]: string
}

interface ClassMappings {
  [key: string]: number
}

const JOB_CLASS_MAP: ClassTranslations = {
  berserker: '捷特巨人',
  dark_knight: '黑骑士',
  kunoichi: '女忍者',
  lahn: '兰',
  maehwa: '梅花',
  musa: '武士',
  ninja: '忍者',
  ranger: '游侠',
  sorceress: '魔女',
  tamer: '苏琅',
  valkyrie: '女武神',
  warrior: '战士',
  witch: '女巫',
  wizard: '魔法师',
}

const JOB_CLASS_TO_NUMBER_MAP: ClassMappings = {
  捷特巨人: 0,
  游侠: 1,
  魔女: 2,
  苏琅: 3,
  女武神: 4,
  战士: 5,
  女巫: 6,
  魔法师: 7,
  武士: 8,
  梅花: 9,
  忍者: 10,
  女忍者: 11,
  黑骑士: 12,
  格斗家: 13,
  女斗神: 14,
  兰: 15,
  巡林者: 16,
  纱依: 17,
  守护者: 18,
  哈沙辛: 19,
  诺娃: 20,
  大贤者: 21,
  珂赛尔: 22,
  妲卡尼亚: 23,
  羽士: 24,
  魅狐: 25,
  重力术士: 26,
  道士: 27,
}

const PVE_CLASS_RANKINGS: ClassItem[] = [
  // S 级 (T0)
  {
    id: 1,
    name: '女巫',
    specialization: '继承',
    imageUrl: '6.webp',
    tier: 'T0',
  },
  {
    id: 2,
    name: '守护者',
    specialization: '继承',
    imageUrl: '18.webp',
    tier: 'T0',
  },
  // A 级 (T1)
  {
    id: 3,
    name: '兰',
    specialization: '继承',
    imageUrl: '15.webp',
    tier: 'T1',
    status: 'superHot',
  },
  {
    id: 4,
    name: '忍者',
    specialization: '继承',
    imageUrl: '10.webp',
    tier: 'T1',
  },
  {
    id: 5,
    name: '黑暗骑士',
    specialization: '觉醒',
    imageUrl: '12.webp',
    tier: 'T1',
  },
  {
    id: 6,
    name: '巡林者',
    specialization: '觉醒',
    imageUrl: '16.webp',
    tier: 'T1',
  },
  {
    id: 7,
    name: '战士',
    specialization: '继承',
    imageUrl: '5.webp',
    tier: 'T1',
  },
  // B 级 (T2)
  {
    id: 8,
    name: '哈沙辛',
    specialization: '觉醒',
    imageUrl: '19.webp',
    tier: 'T2',
  },
  {
    id: 9,
    name: '游侠',
    specialization: '觉醒',
    imageUrl: '1.webp',
    tier: 'T2',
  },
  {
    id: 10,
    name: '女斗神',
    specialization: '觉醒',
    imageUrl: '14.webp',
    tier: 'T2',
  },
  {
    id: 11,
    name: '武士',
    specialization: '觉醒',
    imageUrl: '8.webp',
    tier: 'T2',
  },
  {
    id: 12,
    name: '重力术士',
    specialization: '觉醒',
    imageUrl: '26.webp',
    tier: 'T2',
  },
  {
    id: 13,
    name: '守护者',
    specialization: '觉醒',
    imageUrl: '18.webp',
    tier: 'T2',
    status: 'hot',
  },
  {
    id: 14,
    name: '捷特巨人',
    specialization: '继承',
    imageUrl: '0.webp',
    tier: 'T2',
  },
  {
    id: 15,
    name: '女忍者',
    specialization: '觉醒',
    imageUrl: '11.webp',
    tier: 'T2',
  },
  {
    id: 16,
    name: '魔法师',
    specialization: '继承',
    imageUrl: '7.webp',
    tier: 'T2',
  },
  {
    id: 17,
    name: '捷特巨人',
    specialization: '觉醒',
    imageUrl: '0.webp',
    tier: 'T2',
  },
  {
    id: 18,
    name: '女巫',
    specialization: '觉醒',
    imageUrl: '6.webp',
    tier: 'T2',
    status: 'hot',
  },
  {
    id: 19,
    name: '梅花',
    specialization: '觉醒',
    imageUrl: '9.webp',
    tier: 'T2',
  },
  {
    id: 20,
    name: '女忍者',
    specialization: '继承',
    imageUrl: '11.webp',
    tier: 'T2',
  },
  {
    id: 21,
    name: '梅花',
    specialization: '继承',
    imageUrl: '9.webp',
    tier: 'T2',
  },
  {
    id: 22,
    name: '忍者',
    specialization: '觉醒',
    imageUrl: '10.webp',
    tier: 'T2',
  },
  {
    id: 23,
    name: '苏琅',
    specialization: '继承',
    imageUrl: '3.webp',
    tier: 'T2',
  },
  {
    id: 24,
    name: '苏琅',
    specialization: '觉醒',
    imageUrl: '3.webp',
    tier: 'T2',
  },
  {
    id: 25,
    name: '游侠',
    specialization: '继承',
    imageUrl: '1.webp',
    tier: 'T2',
  },
  {
    id: 26,
    name: '魔法师',
    specialization: '觉醒',
    imageUrl: '7.webp',
    tier: 'T2',
  },

  // C 级 (T3)
  {
    id: 40,
    name: '大贤者',
    specialization: '觉醒',
    imageUrl: '21.webp',
    tier: 'T3',
    status: 'hot',
  },
  {
    id: 27,
    name: '魔女',
    specialization: '继承',
    imageUrl: '2.webp',
    tier: 'T3',
  },
  {
    id: 28,
    name: '魔女',
    specialization: '觉醒',
    imageUrl: '2.webp',
    tier: 'T3',
  },
  {
    id: 29,
    name: '哈沙辛',
    specialization: '继承',
    imageUrl: '19.webp',
    tier: 'T3',
  },
  {
    id: 30,
    name: '女武神',
    specialization: '觉醒',
    imageUrl: '4.webp',
    tier: 'T3',
  },
  {
    id: 31,
    name: '战士',
    specialization: '觉醒',
    imageUrl: '5.webp',
    tier: 'T3',
  },
  {
    id: 42,
    name: '珂赛尔',
    specialization: '觉醒',
    imageUrl: '22.webp',
    tier: 'T3',
    status: 'superHot',
  },
  {
    id: 33,
    name: '兰',
    specialization: '觉醒',
    imageUrl: '15.webp',
    tier: 'T3',
  },
  {
    id: 34,
    name: '格斗家',
    specialization: '继承',
    imageUrl: '13.webp',
    tier: 'T3',
  },
  {
    id: 35,
    name: '女斗神',
    specialization: '继承',
    imageUrl: '14.webp',
    tier: 'T3',
  },
  {
    id: 36,
    name: '格斗家',
    specialization: '觉醒',
    imageUrl: '13.webp',
    tier: 'T3',
  },
  {
    id: 37,
    name: '黑暗骑士',
    specialization: '继承',
    imageUrl: '12.webp',
    tier: 'T3',
  },
  {
    id: 43,
    name: '珂赛尔',
    specialization: '继承',
    imageUrl: '22.webp',
    tier: 'T3',
    status: 'superHot',
  },
  // D 级 (T4)
  {
    id: 38,
    name: '武士',
    specialization: '继承',
    imageUrl: '8.webp',
    tier: 'T4',
  },
  {
    id: 41,
    name: '大贤者',
    specialization: '继承',
    imageUrl: '21.webp',
    tier: 'T4',
    status: 'hot',
  },
  {
    id: 39,
    name: '女武神',
    specialization: '继承',
    imageUrl: '4.webp',
    tier: 'T4',
  },
]

const PVE_EARLY_CLASS_RANKINGS: ClassItem[] = [
  {
    id: 14,
    name: '捷特巨人',
    specialization: '继承',
    imageUrl: '0.webp',
    tier: 'T0',
  },
  {
    id: 11,
    name: '武士',
    specialization: '觉醒',
    imageUrl: '8.webp',
    tier: 'T0',
  },
  {
    id: 6,
    name: '巡林者',
    specialization: '觉醒',
    imageUrl: '16.webp',
    tier: 'T0',
  },
  {
    id: 7,
    name: '战士',
    specialization: '继承',
    imageUrl: '5.webp',
    tier: 'T1',
  },
  {
    id: 25,
    name: '游侠',
    specialization: '继承',
    imageUrl: '1.webp',
    tier: 'T1',
  },
  {
    id: 38,
    name: '武士',
    specialization: '继承',
    imageUrl: '8.webp',
    tier: 'T1',
  },
  {
    id: 19,
    name: '梅花',
    specialization: '觉醒',
    imageUrl: '9.webp',
    tier: 'T1',
  },
  {
    id: 21,
    name: '梅花',
    specialization: '继承',
    imageUrl: '9.webp',
    tier: 'T1',
  },
  {
    id: 4,
    name: '忍者',
    specialization: '继承',
    imageUrl: '10.webp',
    tier: 'T1',
  },
  {
    id: 16,
    name: '魔法师',
    specialization: '继承',
    imageUrl: '7.webp',
    tier: 'T1',
  },
  {
    id: 1,
    name: '女巫',
    specialization: '继承',
    imageUrl: '6.webp',
    tier: 'T1',
  },
  {
    id: 5,
    name: '黑暗骑士',
    specialization: '觉醒',
    imageUrl: '12.webp',
    tier: 'T1',
  },
  {
    id: 36,
    name: '格斗家',
    specialization: '觉醒',
    imageUrl: '13.webp',
    tier: 'T1',
  },
  {
    id: 33,
    name: '兰',
    specialization: '觉醒',
    imageUrl: '15.webp',
    tier: 'T1',
  },
  {
    id: 3,
    name: '兰',
    specialization: '继承',
    imageUrl: '15.webp',
    tier: 'T1',
  },
  {
    id: 31,
    name: '战士',
    specialization: '觉醒',
    imageUrl: '5.webp',
    tier: 'T2',
  },
  {
    id: 28,
    name: '魔女',
    specialization: '觉醒',
    imageUrl: '2.webp',
    tier: 'T2',
  },
  {
    id: 9,
    name: '游侠',
    specialization: '觉醒',
    imageUrl: '1.webp',
    tier: 'T2',
  },
  {
    id: 17,
    name: '捷特巨人',
    specialization: '觉醒',
    imageUrl: '0.webp',
    tier: 'T2',
  },
  {
    id: 24,
    name: '苏琅',
    specialization: '觉醒',
    imageUrl: '3.webp',
    tier: 'T2',
  },
  {
    id: 23,
    name: '苏琅',
    specialization: '继承',
    imageUrl: '3.webp',
    tier: 'T2',
  },
  {
    id: 30,
    name: '女武神',
    specialization: '觉醒',
    imageUrl: '4.webp',
    tier: 'T2',
  },
  {
    id: 15,
    name: '女忍者',
    specialization: '觉醒',
    imageUrl: '11.webp',
    tier: 'T2',
  },
  {
    id: 20,
    name: '女忍者',
    specialization: '继承',
    imageUrl: '11.webp',
    tier: 'T2',
  },
  {
    id: 22,
    name: '忍者',
    specialization: '觉醒',
    imageUrl: '10.webp',
    tier: 'T2',
  },
  {
    id: 26,
    name: '魔法师',
    specialization: '觉醒',
    imageUrl: '7.webp',
    tier: 'T2',
  },
  {
    id: 18,
    name: '女巫',
    specialization: '觉醒',
    imageUrl: '6.webp',
    tier: 'T2',
  },
  {
    id: 37,
    name: '黑暗骑士',
    specialization: '继承',
    imageUrl: '12.webp',
    tier: 'T2',
  },
  {
    id: 10,
    name: '女斗神',
    specialization: '觉醒',
    imageUrl: '14.webp',
    tier: 'T2',
  },
  {
    id: 8,
    name: '哈沙辛',
    specialization: '觉醒',
    imageUrl: '19.webp',
    tier: 'T2',
  },
  {
    id: 40,
    name: '大贤者',
    specialization: '觉醒',
    imageUrl: '21.webp',
    tier: 'T2',
    status: 'hot',
  },
  {
    id: 41,
    name: '大贤者',
    specialization: '继承',
    imageUrl: '21.webp',
    tier: 'T2',
    status: 'hot',
  },
  {
    id: 42,
    name: '珂赛尔',
    specialization: '觉醒',
    imageUrl: '22.webp',
    tier: 'T2',
    status: 'superHot',
  },
  {
    id: 43,
    name: '珂赛尔',
    specialization: '继承',
    imageUrl: '22.webp',
    tier: 'T2',
    status: 'superHot',
  },
  {
    id: 12,
    name: '重力术士',
    specialization: '觉醒',
    imageUrl: '26.webp',
    tier: 'T2',
  },
  {
    id: 2,
    name: '守护者',
    specialization: '继承',
    imageUrl: '18.webp',
    tier: 'T3',
  },
  {
    id: 27,
    name: '魔女',
    specialization: '继承',
    imageUrl: '2.webp',
    tier: 'T4',
  },
  {
    id: 34,
    name: '格斗家',
    specialization: '继承',
    imageUrl: '13.webp',
    tier: 'T4',
  },
  {
    id: 35,
    name: '女斗神',
    specialization: '继承',
    imageUrl: '14.webp',
    tier: 'T4',
  },
  {
    id: 39,
    name: '女武神',
    specialization: '继承',
    imageUrl: '4.webp',
    tier: 'T4',
  },
  {
    id: 13,
    name: '守护者',
    specialization: '觉醒',
    imageUrl: '18.webp',
    tier: 'T4',
  },
  {
    id: 29,
    name: '哈沙辛',
    specialization: '继承',
    imageUrl: '19.webp',
    tier: 'T4',
  },
]

const PVE_MID_CLASS_RANKINGS: ClassItem[] = [
  {
    id: 3,
    name: '兰',
    specialization: '继承',
    imageUrl: '15.webp',
    tier: 'T0',
  },
  {
    id: 6,
    name: '巡林者',
    specialization: '觉醒',
    imageUrl: '16.webp',
    tier: 'T0',
  },
  {
    id: 7,
    name: '战士',
    specialization: '继承',
    imageUrl: '5.webp',
    tier: 'T1',
  },
  {
    id: 17,
    name: '捷特巨人',
    specialization: '觉醒',
    imageUrl: '0.webp',
    tier: 'T1',
  },
  {
    id: 14,
    name: '捷特巨人',
    specialization: '继承',
    imageUrl: '0.webp',
    tier: 'T1',
  },
  {
    id: 24,
    name: '苏琅',
    specialization: '觉醒',
    imageUrl: '3.webp',
    tier: 'T1',
  },
  {
    id: 23,
    name: '苏琅',
    specialization: '继承',
    imageUrl: '3.webp',
    tier: 'T1',
  },
  {
    id: 11,
    name: '武士',
    specialization: '觉醒',
    imageUrl: '8.webp',
    tier: 'T1',
  },
  {
    id: 38,
    name: '武士',
    specialization: '继承',
    imageUrl: '8.webp',
    tier: 'T1',
  },
  {
    id: 30,
    name: '女武神',
    specialization: '觉醒',
    imageUrl: '4.webp',
    tier: 'T1',
  },
  {
    id: 22,
    name: '忍者',
    specialization: '觉醒',
    imageUrl: '10.webp',
    tier: 'T1',
  },
  {
    id: 4,
    name: '忍者',
    specialization: '继承',
    imageUrl: '10.webp',
    tier: 'T1',
  },
  {
    id: 26,
    name: '魔法师',
    specialization: '觉醒',
    imageUrl: '7.webp',
    tier: 'T1',
  },
  {
    id: 16,
    name: '魔法师',
    specialization: '继承',
    imageUrl: '7.webp',
    tier: 'T1',
  },
  {
    id: 18,
    name: '女巫',
    specialization: '觉醒',
    imageUrl: '6.webp',
    tier: 'T1',
  },
  {
    id: 1,
    name: '女巫',
    specialization: '继承',
    imageUrl: '6.webp',
    tier: 'T1',
  },
  {
    id: 5,
    name: '黑暗骑士',
    specialization: '觉醒',
    imageUrl: '12.webp',
    tier: 'T1',
  },
  {
    id: 36,
    name: '格斗家',
    specialization: '觉醒',
    imageUrl: '13.webp',
    tier: 'T1',
  },
  {
    id: 33,
    name: '兰',
    specialization: '觉醒',
    imageUrl: '15.webp',
    tier: 'T1',
  },
  {
    id: 2,
    name: '守护者',
    specialization: '继承',
    imageUrl: '18.webp',
    tier: 'T1',
  },
  {
    id: 40,
    name: '大贤者',
    specialization: '觉醒',
    imageUrl: '21.webp',
    tier: 'T1',
    status: 'hot',
  },
  {
    id: 41,
    name: '大贤者',
    specialization: '继承',
    imageUrl: '21.webp',
    tier: 'T1',
    status: 'hot',
  },
  {
    id: 19,
    name: '梅花',
    specialization: '觉醒',
    imageUrl: '9.webp',
    tier: 'T2',
  },
  {
    id: 10,
    name: '女斗神',
    specialization: '觉醒',
    imageUrl: '14.webp',
    tier: 'T2',
  },
  {
    id: 31,
    name: '战士',
    specialization: '觉醒',
    imageUrl: '5.webp',
    tier: 'T2',
  },
  {
    id: 28,
    name: '魔女',
    specialization: '觉醒',
    imageUrl: '2.webp',
    tier: 'T2',
  },
  {
    id: 27,
    name: '魔女',
    specialization: '继承',
    imageUrl: '2.webp',
    tier: 'T2',
  },
  {
    id: 9,
    name: '游侠',
    specialization: '觉醒',
    imageUrl: '1.webp',
    tier: 'T2',
  },
  {
    id: 25,
    name: '游侠',
    specialization: '继承',
    imageUrl: '1.webp',
    tier: 'T2',
  },
  {
    id: 21,
    name: '梅花',
    specialization: '继承',
    imageUrl: '9.webp',
    tier: 'T2',
  },
  {
    id: 15,
    name: '女忍者',
    specialization: '觉醒',
    imageUrl: '11.webp',
    tier: 'T2',
  },
  {
    id: 20,
    name: '女忍者',
    specialization: '继承',
    imageUrl: '11.webp',
    tier: 'T2',
  },
  {
    id: 37,
    name: '黑暗骑士',
    specialization: '继承',
    imageUrl: '12.webp',
    tier: 'T2',
  },
  {
    id: 35,
    name: '女斗神',
    specialization: '继承',
    imageUrl: '14.webp',
    tier: 'T2',
  },
  {
    id: 13,
    name: '守护者',
    specialization: '觉醒',
    imageUrl: '18.webp',
    tier: 'T2',
  },
  {
    id: 34,
    name: '格斗家',
    specialization: '继承',
    imageUrl: '13.webp',
    tier: 'T2',
  },
  {
    id: 8,
    name: '哈沙辛',
    specialization: '觉醒',
    imageUrl: '19.webp',
    tier: 'T2',
  },
  {
    id: 29,
    name: '哈沙辛',
    specialization: '继承',
    imageUrl: '19.webp',
    tier: 'T2',
  },
  {
    id: 42,
    name: '珂赛尔',
    specialization: '觉醒',
    imageUrl: '22.webp',
    tier: 'T2',
    status: 'superHot',
  },
  {
    id: 43,
    name: '珂赛尔',
    specialization: '继承',
    imageUrl: '22.webp',
    tier: 'T2',
    status: 'superHot',
  },
  {
    id: 12,
    name: '重力术士',
    specialization: '觉醒',
    imageUrl: '26.webp',
    tier: 'T2',
  },
  {
    id: 39,
    name: '女武神',
    specialization: '继承',
    imageUrl: '4.webp',
    tier: 'T3',
  },
]

const PVE_END_CLASS_RANKINGS: ClassItem[] = [
  {
    id: 28,
    name: '魔女',
    specialization: '觉醒',
    imageUrl: '2.webp',
    tier: 'T0',
  },
  {
    id: 4,
    name: '忍者',
    specialization: '继承',
    imageUrl: '10.webp',
    tier: 'T0',
  },
  {
    id: 1,
    name: '女巫',
    specialization: '继承',
    imageUrl: '6.webp',
    tier: 'T0',
  },
  {
    id: 3,
    name: '兰',
    specialization: '继承',
    imageUrl: '15.webp',
    tier: 'T0',
  },
  {
    id: 2,
    name: '守护者',
    specialization: '继承',
    imageUrl: '18.webp',
    tier: 'T0',
  },
  {
    id: 7,
    name: '战士',
    specialization: '继承',
    imageUrl: '5.webp',
    tier: 'T1',
  },
  {
    id: 9,
    name: '游侠',
    specialization: '觉醒',
    imageUrl: '1.webp',
    tier: 'T1',
  },
  {
    id: 17,
    name: '捷特巨人',
    specialization: '觉醒',
    imageUrl: '0.webp',
    tier: 'T1',
  },
  {
    id: 24,
    name: '苏琅',
    specialization: '觉醒',
    imageUrl: '3.webp',
    tier: 'T1',
  },
  {
    id: 23,
    name: '苏琅',
    specialization: '继承',
    imageUrl: '3.webp',
    tier: 'T1',
  },
  {
    id: 38,
    name: '武士',
    specialization: '继承',
    imageUrl: '8.webp',
    tier: 'T1',
  },
  {
    id: 19,
    name: '梅花',
    specialization: '觉醒',
    imageUrl: '9.webp',
    tier: 'T1',
  },
  {
    id: 21,
    name: '梅花',
    specialization: '继承',
    imageUrl: '9.webp',
    tier: 'T1',
  },
  {
    id: 22,
    name: '忍者',
    specialization: '觉醒',
    imageUrl: '10.webp',
    tier: 'T1',
  },
  {
    id: 26,
    name: '魔法师',
    specialization: '觉醒',
    imageUrl: '7.webp',
    tier: 'T1',
  },
  {
    id: 16,
    name: '魔法师',
    specialization: '继承',
    imageUrl: '7.webp',
    tier: 'T1',
  },
  {
    id: 18,
    name: '女巫',
    specialization: '觉醒',
    imageUrl: '6.webp',
    tier: 'T1',
  },
  {
    id: 5,
    name: '黑暗骑士',
    specialization: '觉醒',
    imageUrl: '12.webp',
    tier: 'T1',
  },
  {
    id: 37,
    name: '黑暗骑士',
    specialization: '继承',
    imageUrl: '12.webp',
    tier: 'T1',
  },
  {
    id: 36,
    name: '格斗家',
    specialization: '觉醒',
    imageUrl: '13.webp',
    tier: 'T1',
  },
  {
    id: 34,
    name: '格斗家',
    specialization: '继承',
    imageUrl: '13.webp',
    tier: 'T1',
  },
  {
    id: 10,
    name: '女斗神',
    specialization: '觉醒',
    imageUrl: '14.webp',
    tier: 'T1',
  },
  {
    id: 6,
    name: '巡林者',
    specialization: '觉醒',
    imageUrl: '16.webp',
    tier: 'T1',
  },
  {
    id: 13,
    name: '守护者',
    specialization: '觉醒',
    imageUrl: '18.webp',
    tier: 'T1',
  },
  {
    id: 29,
    name: '哈沙辛',
    specialization: '继承',
    imageUrl: '19.webp',
    tier: 'T1',
  },
  {
    id: 40,
    name: '大贤者',
    specialization: '觉醒',
    imageUrl: '21.webp',
    tier: 'T1',
    status: 'hot',
  },
  {
    id: 41,
    name: '大贤者',
    specialization: '继承',
    imageUrl: '21.webp',
    tier: 'T1',
    status: 'hot',
  },
  {
    id: 12,
    name: '重力术士',
    specialization: '觉醒',
    imageUrl: '26.webp',
    tier: 'T1',
  },
  {
    id: 31,
    name: '战士',
    specialization: '觉醒',
    imageUrl: '5.webp',
    tier: 'T2',
  },
  {
    id: 27,
    name: '魔女',
    specialization: '继承',
    imageUrl: '2.webp',
    tier: 'T2',
  },
  {
    id: 14,
    name: '捷特巨人',
    specialization: '继承',
    imageUrl: '0.webp',
    tier: 'T2',
  },
  {
    id: 11,
    name: '武士',
    specialization: '觉醒',
    imageUrl: '8.webp',
    tier: 'T2',
  },
  {
    id: 30,
    name: '女武神',
    specialization: '觉醒',
    imageUrl: '4.webp',
    tier: 'T2',
  },
  {
    id: 20,
    name: '女忍者',
    specialization: '继承',
    imageUrl: '11.webp',
    tier: 'T2',
  },
  {
    id: 33,
    name: '兰',
    specialization: '觉醒',
    imageUrl: '15.webp',
    tier: 'T2',
  },
  {
    id: 8,
    name: '哈沙辛',
    specialization: '觉醒',
    imageUrl: '19.webp',
    tier: 'T2',
  },
  {
    id: 42,
    name: '珂赛尔',
    specialization: '觉醒',
    imageUrl: '22.webp',
    tier: 'T2',
    status: 'superHot',
  },
  {
    id: 43,
    name: '珂赛尔',
    specialization: '继承',
    imageUrl: '22.webp',
    tier: 'T2',
    status: 'superHot',
  },
  {
    id: 25,
    name: '游侠',
    specialization: '继承',
    imageUrl: '1.webp',
    tier: 'T3',
  },
  {
    id: 39,
    name: '女武神',
    specialization: '继承',
    imageUrl: '4.webp',
    tier: 'T3',
  },
  {
    id: 15,
    name: '女忍者',
    specialization: '觉醒',
    imageUrl: '11.webp',
    tier: 'T3',
  },
  {
    id: 35,
    name: '女斗神',
    specialization: '继承',
    imageUrl: '14.webp',
    tier: 'T3',
  },
]

const PVP_CLASS_RANKINGS: ClassItem[] = [
  {
    id: 24,
    name: '苏琅',
    specialization: '觉醒',
    imageUrl: '3.webp',
    tier: 'T0',
  },
  {
    id: 23,
    name: '苏琅',
    specialization: '继承',
    imageUrl: '3.webp',
    tier: 'T0',
  },
  {
    id: 9,
    name: '游侠',
    specialization: '觉醒',
    imageUrl: '1.webp',
    tier: 'T0',
  },
  {
    id: 31,
    name: '战士',
    specialization: '觉醒',
    imageUrl: '5.webp',
    tier: 'T0',
  },
  {
    id: 29,
    name: '哈沙辛',
    specialization: '继承',
    imageUrl: '19.webp',
    tier: 'T0',
  },
  {
    id: 8,
    name: '哈沙辛',
    specialization: '觉醒',
    imageUrl: '19.webp',
    tier: 'T0',
  },
  {
    id: 4,
    name: '忍者',
    specialization: '继承',
    imageUrl: '10.webp',
    tier: 'T0',
  },
  {
    id: 20,
    name: '女忍者',
    specialization: '继承',
    imageUrl: '11.webp',
    tier: 'T0',
  },
  {
    id: 15,
    name: '女忍者',
    specialization: '觉醒',
    imageUrl: '11.webp',
    tier: 'T0',
  },
  {
    id: 22,
    name: '忍者',
    specialization: '觉醒',
    imageUrl: '10.webp',
    tier: 'T0',
  },
  {
    id: 39,
    name: '女武神',
    specialization: '继承',
    imageUrl: '4.webp',
    tier: 'T0',
  },
  {
    id: 28,
    name: '魔女',
    specialization: '觉醒',
    imageUrl: '2.webp',
    tier: 'T1',
  },
  {
    id: 27,
    name: '魔女',
    specialization: '继承',
    imageUrl: '2.webp',
    tier: 'T1',
  },
  {
    id: 33,
    name: '兰',
    specialization: '觉醒',
    imageUrl: '15.webp',
    tier: 'T1',
  },
  {
    id: 40,
    name: '大贤者',
    specialization: '觉醒',
    imageUrl: '21.webp',
    tier: 'T1',
    status: 'hot',
  },
  {
    id: 34,
    name: '格斗家',
    specialization: '继承',
    imageUrl: '13.webp',
    tier: 'T1',
  },
  {
    id: 35,
    name: '女斗神',
    specialization: '继承',
    imageUrl: '14.webp',
    tier: 'T1',
  },
  {
    id: 36,
    name: '格斗家',
    specialization: '觉醒',
    imageUrl: '13.webp',
    tier: 'T1',
  },
  {
    id: 17,
    name: '捷特巨人',
    specialization: '觉醒',
    imageUrl: '0.webp',
    tier: 'T1',
  },
  {
    id: 14,
    name: '捷特巨人',
    specialization: '继承',
    imageUrl: '0.webp',
    tier: 'T1',
  },
  {
    id: 42,
    name: '珂赛尔',
    specialization: '觉醒',
    imageUrl: '22.webp',
    tier: 'T1',
    status: 'superHot',
  },
  {
    id: 7,
    name: '战士',
    specialization: '继承',
    imageUrl: '5.webp',
    tier: 'T2',
  },
  {
    id: 2,
    name: '守护者',
    specialization: '继承',
    imageUrl: '18.webp',
    tier: 'T2',
  },
  {
    id: 30,
    name: '女武神',
    specialization: '觉醒',
    imageUrl: '4.webp',
    tier: 'T2',
  },
  {
    id: 37,
    name: '黑暗骑士',
    specialization: '继承',
    imageUrl: '12.webp',
    tier: 'T2',
  },
  {
    id: 5,
    name: '黑暗骑士',
    specialization: '觉醒',
    imageUrl: '12.webp',
    tier: 'T2',
  },
  {
    id: 13,
    name: '守护者',
    specialization: '觉醒',
    imageUrl: '18.webp',
    tier: 'T3',
  },
  {
    id: 19,
    name: '梅花',
    specialization: '觉醒',
    imageUrl: '9.webp',
    tier: 'T3',
  },
  {
    id: 26,
    name: '魔法师',
    specialization: '觉醒',
    imageUrl: '7.webp',
    tier: 'T3',
  },
  {
    id: 11,
    name: '武士',
    specialization: '觉醒',
    imageUrl: '8.webp',
    tier: 'T3',
  },
  {
    id: 21,
    name: '梅花',
    specialization: '继承',
    imageUrl: '9.webp',
    tier: 'T3',
  },
  {
    id: 38,
    name: '武士',
    specialization: '继承',
    imageUrl: '8.webp',
    tier: 'T3',
  },
  {
    id: 10,
    name: '女斗神',
    specialization: '觉醒',
    imageUrl: '14.webp',
    tier: 'T3',
  },
  {
    id: 12,
    name: '重力术士',
    specialization: '觉醒',
    imageUrl: '26.webp',
    tier: 'T3',
  },
  {
    id: 3,
    name: '兰',
    specialization: '继承',
    imageUrl: '15.webp',
    tier: 'T4',
  },
  {
    id: 6,
    name: '巡林者',
    specialization: '觉醒',
    imageUrl: '16.webp',
    tier: 'T4',
  },
  {
    id: 1,
    name: '女巫',
    specialization: '继承',
    imageUrl: '6.webp',
    tier: 'T4',
  },
  {
    id: 16,
    name: '魔法师',
    specialization: '继承',
    imageUrl: '7.webp',
    tier: 'T4',
  },
  {
    id: 25,
    name: '游侠',
    specialization: '继承',
    imageUrl: '1.webp',
    tier: 'T4',
  },
  {
    id: 41,
    name: '大贤者',
    specialization: '继承',
    imageUrl: '21.webp',
    tier: 'T4',
    status: 'hot',
  },
  {
    id: 43,
    name: '珂赛尔',
    specialization: '继承',
    imageUrl: '22.webp',
    tier: 'T4',
    status: 'superHot',
  },
  {
    id: 18,
    name: '女巫',
    specialization: '觉醒',
    imageUrl: '6.webp',
    tier: 'T4',
  },
]

const PVP_LARGE_SCALE_CLASS_RANKINGS: ClassItem[] = [
  {
    id: 30,
    name: '女武神',
    specialization: '觉醒',
    imageUrl: '4.webp',
    tier: 'T0',
  },
  {
    id: 6,
    name: '巡林者',
    specialization: '觉醒',
    imageUrl: '16.webp',
    tier: 'T0',
  },
  {
    id: 25,
    name: '游侠',
    specialization: '继承',
    imageUrl: '1.webp',
    tier: 'T0',
  },
  {
    id: 16,
    name: '魔法师',
    specialization: '继承',
    imageUrl: '7.webp',
    tier: 'T0',
  },
  {
    id: 1,
    name: '女巫',
    specialization: '继承',
    imageUrl: '6.webp',
    tier: 'T0',
  },
  {
    id: 14,
    name: '捷特巨人',
    specialization: '继承',
    imageUrl: '0.webp',
    tier: 'T1',
  },
  {
    id: 3,
    name: '兰',
    specialization: '继承',
    imageUrl: '15.webp',
    tier: 'T1',
  },
  {
    id: 26,
    name: '魔法师',
    specialization: '觉醒',
    imageUrl: '7.webp',
    tier: 'T1',
  },
  {
    id: 2,
    name: '守护者',
    specialization: '继承',
    imageUrl: '18.webp',
    tier: 'T1',
  },
  {
    id: 17,
    name: '捷特巨人',
    specialization: '觉醒',
    imageUrl: '0.webp',
    tier: 'T1',
  },
  {
    id: 12,
    name: '重力术士',
    specialization: '觉醒',
    imageUrl: '26.webp',
    tier: 'T1',
  },
  {
    id: 36,
    name: '格斗家',
    specialization: '觉醒',
    imageUrl: '13.webp',
    tier: 'T2',
  },
  {
    id: 13,
    name: '守护者',
    specialization: '觉醒',
    imageUrl: '18.webp',
    tier: 'T2',
  },
  {
    id: 41,
    name: '大贤者',
    specialization: '继承',
    imageUrl: '21.webp',
    tier: 'T2',
    status: 'hot',
  },
  {
    id: 18,
    name: '女巫',
    specialization: '觉醒',
    imageUrl: '6.webp',
    tier: 'T2',
  },
  {
    id: 11,
    name: '武士',
    specialization: '觉醒',
    imageUrl: '8.webp',
    tier: 'T2',
  },
  {
    id: 5,
    name: '黑暗骑士',
    specialization: '觉醒',
    imageUrl: '12.webp',
    tier: 'T2',
  },
  {
    id: 27,
    name: '魔女',
    specialization: '继承',
    imageUrl: '2.webp',
    tier: 'T2',
  },
  {
    id: 28,
    name: '魔女',
    specialization: '觉醒',
    imageUrl: '2.webp',
    tier: 'T2',
  },
  {
    id: 23,
    name: '苏琅',
    specialization: '继承',
    imageUrl: '3.webp',
    tier: 'T2',
  },
  {
    id: 24,
    name: '苏琅',
    specialization: '觉醒',
    imageUrl: '3.webp',
    tier: 'T2',
  },
  {
    id: 33,
    name: '兰',
    specialization: '觉醒',
    imageUrl: '15.webp',
    tier: 'T2',
  },
  {
    id: 43,
    name: '珂赛尔',
    specialization: '继承',
    imageUrl: '22.webp',
    tier: 'T3',
    status: 'superHot',
  },
  {
    id: 7,
    name: '战士',
    specialization: '继承',
    imageUrl: '5.webp',
    tier: 'T3',
  },
  {
    id: 19,
    name: '梅花',
    specialization: '觉醒',
    imageUrl: '9.webp',
    tier: 'T3',
  },
  {
    id: 37,
    name: '黑暗骑士',
    specialization: '继承',
    imageUrl: '12.webp',
    tier: 'T3',
  },
  {
    id: 42,
    name: '珂赛尔',
    specialization: '觉醒',
    imageUrl: '22.webp',
    tier: 'T3',
    status: 'superHot',
  },
  {
    id: 4,
    name: '忍者',
    specialization: '继承',
    imageUrl: '10.webp',
    tier: 'T3',
  },
  {
    id: 22,
    name: '忍者',
    specialization: '觉醒',
    imageUrl: '10.webp',
    tier: 'T3',
  },
  {
    id: 15,
    name: '女忍者',
    specialization: '觉醒',
    imageUrl: '11.webp',
    tier: 'T3',
  },
  {
    id: 20,
    name: '女忍者',
    specialization: '继承',
    imageUrl: '11.webp',
    tier: 'T3',
  },
  {
    id: 39,
    name: '女武神',
    specialization: '继承',
    imageUrl: '4.webp',
    tier: 'T3',
  },
  {
    id: 40,
    name: '大贤者',
    specialization: '觉醒',
    imageUrl: '21.webp',
    tier: 'T3',
    status: 'hot',
  },
  {
    id: 21,
    name: '梅花',
    specialization: '继承',
    imageUrl: '9.webp',
    tier: 'T3',
  },
  {
    id: 31,
    name: '战士',
    specialization: '觉醒',
    imageUrl: '5.webp',
    tier: 'T3',
  },
  {
    id: 10,
    name: '女斗神',
    specialization: '觉醒',
    imageUrl: '14.webp',
    tier: 'T3',
  },
  {
    id: 8,
    name: '哈沙辛',
    specialization: '觉醒',
    imageUrl: '19.webp',
    tier: 'T4',
  },
  {
    id: 29,
    name: '哈沙辛',
    specialization: '继承',
    imageUrl: '19.webp',
    tier: 'T4',
  },
  {
    id: 38,
    name: '武士',
    specialization: '继承',
    imageUrl: '8.webp',
    tier: 'T4',
  },
  {
    id: 35,
    name: '女斗神',
    specialization: '继承',
    imageUrl: '14.webp',
    tier: 'T4',
  },
  {
    id: 9,
    name: '游侠',
    specialization: '觉醒',
    imageUrl: '1.webp',
    tier: 'T4',
  },
  {
    id: 34,
    name: '格斗家',
    specialization: '继承',
    imageUrl: '13.webp',
    tier: 'T4',
  },
]

export {
  API_BASE_URL,
  BASE_ASSET_URL,
  BASE_IMAGE_URL,
  BASE_PA_IMAGE_URL,
  BASE_IMAGE_BEAUTY_ALBUM_COVER_URL,
  BASE_IMAGE_CLASS_URL,
  APP_NAME,
  APP_SUFFIX,
  WEBSITE_DOMAIN,
  SCHEMA,
  JOB_CLASS_MAP,
  JOB_CLASS_TO_NUMBER_MAP,
  PVE_CLASS_RANKINGS,
  PVE_EARLY_CLASS_RANKINGS,
  PVE_MID_CLASS_RANKINGS,
  PVE_END_CLASS_RANKINGS,
  PVP_CLASS_RANKINGS,
  PVP_LARGE_SCALE_CLASS_RANKINGS,
  MOCK_GET_GLOBAL,
}
