const pages = [
  'pages/index/index',
  'pages/news/index',
  'pages/blank/index',
  'pages/boss-timer/index',
  'pages/mastery-brackets/index',
  'pages/grind-tracker/BestGrindSpots',
  'pages/grind-tracker/TierList',
  'pages/enhancing-simulator/index',
  'pages/grind-timer/index',
  'pages/imperial-crates/index',
  'pages/beauty-album/index',
  'pages/grind-tracker/global/index',
  'pages/monster-ap-caps/index',
  'pages/beauty-album/download',
  'pages/apdpdr-brackets/index',
  'pages/skill-addon-planner/index',
  'pages/tier-list/index',
  'pages/profile/index',
  'pages/grind-tracker/global/globalDetail',
  'pages/login/index',
  'pages/post/index',
  'pages/post/guide-post',
]
export default defineAppConfig({
  animation: true,
  entryPagePath: 'pages/index/index',
  lazyCodeLoading: 'requiredComponents',
  pages,
  tabBar: {
    color: '#ffffff',
    selectedColor: '#fefefe',
    backgroundColor: '#444444',
    list: [
      {
        pagePath: 'pages/index/index',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home-selected.png',
        text: '首页',
      },
      {
        pagePath: 'pages/post/index',
        iconPath: 'assets/tabbar/news.png',
        selectedIconPath: 'assets/tabbar/news-selected.png',
        text: '消息',
      },
      {
        pagePath: 'pages/login/index',
        iconPath: 'assets/tabbar/profile.png',
        selectedIconPath: 'assets/tabbar/profile-selected.png',
        text: '我的',
      },
    ],
  },
  window: {
    backgroundTextStyle: 'dark',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: '黑沙盒子',
    navigationBarTextStyle: 'black',
  },
  enableShareAppMessage: true,
})
